# Generated by Django 2.1.3 on 2018-11-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField()),
                ('summoner_id', models.BigIntegerField()),
                ('summoner_name', models.CharField(max_length=20)),
                ('damage_dealt', models.BigIntegerField()),
                ('damage_taken', models.BigIntegerField()),
                ('damage_dealt_to_turrets', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('username_lower', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('creation_time', models.BigIntegerField()),
            ],
        ),
    ]
